### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by retaLazyCodes** [retaLazyCodes/the8Agency-challenge#1]
- [ ]  Improve the responsive design for mobile devices
- [ ]  Show link to ***`/attendees`*** on alert when submit form
- [ ]  Implement pagination on data-table
